sudo: false
warnings_are_errors: false
env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"

matrix:
  include:

  - language: r
    cache: packages
    before_install:
    - cd R

  - language: python
    python: 3.6
    before_install:
    - cd python
    install:
    - pip install .
    script:
    - python setup.py test